# Generated by Django 4.2.11 on 2024-03-30 06:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstclass',
            name='height',
            field=models.IntegerField(default=160, validators=[django.core.validators.MinValueValidator(120), django.core.validators.MaxValueValidator(300)]),
        ),
        migrations.AlterField(
            model_name='firstclass',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
