# Generated by Django 4.2.11 on 2024-04-01 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SimpleModel',
            new_name='ReviewModel',
        ),
    ]
